title: Products
template: default
layout: layout
taxonomies:
  - types
revisions: true
route: '/products/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
